import React from 'react'
import { node, oneOfType, func } from 'prop-types'

import css from './SizesOutput.sass'

/** Outputs sizes for provided component.
 * Sizes should be generated by the function:
 *
 * import { makeParamsObjFromSassMap } from '../lib'
 *
 * Or have the same structure
 */
const SizesOutput = ({
  OutputComponent, Component, ...props
}) => {
  const ComponentEx = OutputComponent || Component

  return (
    <div className={css.root}>
      <h4>Sizes: </h4>
      <table style={{ borderSpacing: '25px' }}>
        <tbody>
          {Object.keys(Component.size).map(size => (
            <tr key={`${size}-${Component.size[size][1]}`}>
              <td className={css.size}>
                {size}
              </td>
              <td className={css.label}>
                {Component.size[size][1]}
              </td>
              <td className={css.component}>
                <ComponentEx size={Component.size[size][0]} {...props} />
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

SizesOutput.propTypes = {
  /** Component to output sizes for */
  Component: oneOfType([node, func]),
  /** Component to output sizes for */
  OutputComponent: oneOfType([node, func]),
}

export { SizesOutput }

/* Default exports will be deprecated soon, use named exports instead */
export default SizesOutput
