import React from 'react'
import { node, oneOfType, func, string, shape } from 'prop-types'

import css from './PropsetOutput.sass'

/** Outputs propset for provided component.
 * Props should be generated by the function:
 *
 * import { makeParamsObjFromSassMap } from '../lib'
 *
 * Or have the same structure
 */
const PropsetOutput = ({
  OutputComponent,
  Component,
  propset,
  propsetMap,
  ...props
}) => {
  const ComponentEx = OutputComponent || Component

  return (
    <div className={css.root}>
      <h4>{propset}: </h4>
      <table style={{ borderSpacing: '25px' }}>
        <tbody>
          {Object.keys(Component[propset]).map(prop => (
            <tr key={`${prop}-${Component[propset][prop][1]}`}>
              <td className={css.prop}>
                {prop}
              </td>
              <td className={css.label}>
                {JSON.stringify(Component[propset][prop][1])}
              </td>
              <td className={css.component}>
                <ComponentEx
                  {...{ [propsetMap[propset] || propset]: Component[propset][prop][0] }}
                  {...props}
                />
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

PropsetOutput.propTypes = {
  /** Component to output sizes for */
  Component: oneOfType([node, func]),
  /** Component to output sizes for */
  OutputComponent: oneOfType([node, func]),
  /** Propset name for output */
  propset: string,
  /** Propset map for output */
  propsetMap: shape(),
}

PropsetOutput.defaultProps = {
  propsetMap: {},
}

export { PropsetOutput }

/* Default exports will be deprecated soon, use named exports instead */
export default PropsetOutput
